"""Generate the courtside logger's seed data and app icons.

The logger (docs/logger/) is a static page, so anything it needs to know about
the team has to be baked in. This writes:

  docs/logger/seed.js       roster from stats.py, plus venues and opponents seen
                            in game_logs/ for the new-game autocomplete
  docs/logger/icon-192.png  home-screen icons (iOS wants a real raster image)
  docs/logger/icon-512.png

Run it after editing the roster in scripts/stats.py or adding a game log:

    python3 scripts/build_logger.py
"""

import json
import os
import struct
import sys
import zlib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from stats import players

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAME_LOG_DIR = os.path.join(ROOT, "game_logs")
OUTPUT_DIR = os.path.join(ROOT, "docs", "logger")

NAVY = (46, 87, 166)
BALL = (240, 138, 40)


def recent_first(values):
    """Unique values, most recently used first (game logs sort by date)."""
    seen = []
    for value in values:
        if value not in seen:
            seen.append(value)
    return seen


def read_game_history():
    logs = sorted((entry for entry in os.listdir(GAME_LOG_DIR) if not entry.startswith(".")),
                  reverse=True)
    venues = []
    opponents = []
    for log in logs:
        (_, venue, opponent) = log.split(".")
        venues.append(venue)
        opponents.append(opponent)
    return recent_first(venues), recent_first(opponents)


def write_seed(venues, opponents):
    seed = {"roster": players, "venues": venues, "opponents": opponents}
    path = os.path.join(OUTPUT_DIR, "seed.js")
    with open(path, "w", encoding="utf-8") as file:
        file.write("/* GENERATED BY scripts/build_logger.py -- do not edit. */\n")
        file.write("window.GALAXY_SEED = ")
        file.write(json.dumps(seed, indent=2))
        file.write(";\n")
    return path


def basketball_pixel(x, y, size):
    """Color for one sample of the app icon: an orange ball with navy seams."""
    (cx, cy) = (size / 2.0, size / 2.0)
    (dx, dy) = (x - cx, y - cy)
    radius = (dx * dx + dy * dy) ** 0.5
    ball = 0.38 * size
    seam = 0.032 * size

    if radius > ball:
        return NAVY
    # Vertical and horizontal seams, plus two curved seams bowing left and right.
    if abs(dx) < seam or abs(dy) < seam:
        return NAVY
    # The two bowed seams are arcs of circles centered off to each side, sized so
    # they meet the ball exactly at its top and bottom poles.
    offset = 0.40 * ball
    arc = (offset * offset + ball * ball) ** 0.5
    for direction in (-1, 1):
        (ox, oy) = (dx + direction * offset, dy)
        if abs((ox * ox + oy * oy) ** 0.5 - arc) < seam:
            return NAVY
    return BALL


def write_icon(size, samples=3):
    """Write a supersampled RGB PNG without needing an imaging library."""
    rows = []
    for y in range(size):
        row = bytearray()
        for x in range(size):
            (red, green, blue) = (0, 0, 0)
            for sy in range(samples):
                for sx in range(samples):
                    pixel = basketball_pixel(x + (sx + 0.5) / samples,
                                             y + (sy + 0.5) / samples, size)
                    red += pixel[0]
                    green += pixel[1]
                    blue += pixel[2]
            total = samples * samples
            row += bytes((red // total, green // total, blue // total))
        rows.append(b"\x00" + bytes(row))

    def chunk(tag, data):
        return (struct.pack(">I", len(data)) + tag + data +
                struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    header = struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0)  # 8-bit truecolor
    png = (b"\x89PNG\r\n\x1a\n" +
           chunk(b"IHDR", header) +
           chunk(b"IDAT", zlib.compress(b"".join(rows), 9)) +
           chunk(b"IEND", b""))

    path = os.path.join(OUTPUT_DIR, f"icon-{size}.png")
    with open(path, "wb") as file:
        file.write(png)
    return path


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    (venues, opponents) = read_game_history()
    written = [write_seed(venues, opponents), write_icon(192), write_icon(512)]
    for path in written:
        print(f"Wrote {path}")


if __name__ == "__main__":
    main()
