"""Generate the courtside logger's seed data and app icons.

The logger (docs/logger/) is a static page, so anything it needs to know about
the team has to be baked in. This writes:

  docs/logger/seed.js       roster from stats.py, plus venues and opponents seen
                            in game_logs/ for the new-game autocomplete
  docs/logger/icon-192.png  home-screen icons (iOS wants a real raster image)
  docs/logger/icon-512.png

It also stamps a build id -- a hash of the app's own files -- into seed.js, where
the Game menu shows it, and into the service worker's cache name, so the offline
cache rolls exactly when the app changes and never when it does not. That is what
stops a phone serving a new index.html beside an old app.js.

Run it after editing the roster in scripts/stats.py or adding a game log:

    python3 scripts/build_logger.py
"""

import hashlib
import json
import os
import re
import struct
import sys
import zlib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from stats import players

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAME_LOG_DIR = os.path.join(ROOT, "game_logs")
OUTPUT_DIR = os.path.join(ROOT, "docs", "logger")

NAVY = (46, 87, 166)
BALL = (240, 138, 40)


def recent_first(values):
    """Unique values, most recently used first (game logs sort by date)."""
    seen = []
    for value in values:
        if value not in seen:
            seen.append(value)
    return seen


def read_game_history():
    logs = sorted((entry for entry in os.listdir(GAME_LOG_DIR) if not entry.startswith(".")),
                  reverse=True)
    venues = []
    opponents = []
    for log in logs:
        (_, venue, opponent) = log.split(".")
        venues.append(venue)
        opponents.append(opponent)
    return recent_first(venues), recent_first(opponents)


# The files whose contents decide the build id. seed.js is not among them: it is
# what carries the id, so hashing it would chase its own tail. Its *data* goes in
# instead, which is the part a phone would notice.
HASHED_FILES = ["index.html", "app.css", "app.js", "logstats.js",
                "manifest.webmanifest", "icon-192.png", "icon-512.png"]


VERSION_QUERY = re.compile(r"\?v=[A-Za-z0-9]*")
VERSION_QUERY_BYTES = re.compile(rb"\?v=[A-Za-z0-9]*")


def build_id(seed):
    """A short hash of everything a phone downloads, so a rebuilt app is always
    recognisably a different build and an unchanged one is always the same.

    The ?v= stamps are blanked before hashing: they are derived from this hash,
    so leaving them in would make the id depend on itself."""
    digest = hashlib.sha256()
    digest.update(json.dumps(seed, sort_keys=True).encode("utf-8"))
    for name in HASHED_FILES:
        path = os.path.join(OUTPUT_DIR, name)
        with open(path, "rb") as file:
            content = file.read()
        if name.endswith((".html", ".js", ".css")):
            content = VERSION_QUERY_BYTES.sub(b"?v=", content)
        digest.update(content)
    return digest.hexdigest()[:10]


def stamp(name, build, *, cache_name=False):
    """Point a file's asset URLs -- and the service worker's cache -- at this
    build. Versioned URLs are what make an update land whole: index.html is
    revalidated every open, and the URLs it names hold one build's bytes only.
    Without them the browser's own max-age can pair a new page with old code."""
    path = os.path.join(OUTPUT_DIR, name)
    with open(path, encoding="utf-8") as file:
        source = file.read()
    stamped = VERSION_QUERY.sub(f"?v={build}", source)
    if cache_name:
        stamped = re.sub(r'var CACHE = "galaxy-logger-[^"]*";',
                         f'var CACHE = "galaxy-logger-{build}";', stamped, count=1)
        if 'var CACHE = "galaxy-logger-' not in stamped:
            raise SystemExit("build_logger.py: no CACHE line in sw.js")
    if VERSION_QUERY.search(source) is None:
        raise SystemExit(f"build_logger.py: no ?v= stamps left in {name}")
    with open(path, "w", encoding="utf-8") as file:
        file.write(stamped)
    return path


def write_seed(venues, opponents):
    seed = {"roster": players, "venues": venues, "opponents": opponents}
    seed["build"] = build_id(seed)
    path = os.path.join(OUTPUT_DIR, "seed.js")
    with open(path, "w", encoding="utf-8") as file:
        file.write("/* GENERATED BY scripts/build_logger.py -- do not edit. */\n")
        file.write("window.GALAXY_SEED = ")
        file.write(json.dumps(seed, indent=2))
        file.write(";\n")
    return path


def basketball_pixel(x, y, size):
    """Color for one sample of the app icon: an orange ball with navy seams."""
    (cx, cy) = (size / 2.0, size / 2.0)
    (dx, dy) = (x - cx, y - cy)
    radius = (dx * dx + dy * dy) ** 0.5
    ball = 0.38 * size
    seam = 0.032 * size

    if radius > ball:
        return NAVY
    # Vertical and horizontal seams, plus two curved seams bowing left and right.
    if abs(dx) < seam or abs(dy) < seam:
        return NAVY
    # The two bowed seams are arcs of circles centered off to each side, sized so
    # they meet the ball exactly at its top and bottom poles.
    offset = 0.40 * ball
    arc = (offset * offset + ball * ball) ** 0.5
    for direction in (-1, 1):
        (ox, oy) = (dx + direction * offset, dy)
        if abs((ox * ox + oy * oy) ** 0.5 - arc) < seam:
            return NAVY
    return BALL


def write_icon(size, samples=3):
    """Write a supersampled RGB PNG without needing an imaging library."""
    rows = []
    for y in range(size):
        row = bytearray()
        for x in range(size):
            (red, green, blue) = (0, 0, 0)
            for sy in range(samples):
                for sx in range(samples):
                    pixel = basketball_pixel(x + (sx + 0.5) / samples,
                                             y + (sy + 0.5) / samples, size)
                    red += pixel[0]
                    green += pixel[1]
                    blue += pixel[2]
            total = samples * samples
            row += bytes((red // total, green // total, blue // total))
        rows.append(b"\x00" + bytes(row))

    def chunk(tag, data):
        return (struct.pack(">I", len(data)) + tag + data +
                struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    header = struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0)  # 8-bit truecolor
    png = (b"\x89PNG\r\n\x1a\n" +
           chunk(b"IHDR", header) +
           chunk(b"IDAT", zlib.compress(b"".join(rows), 9)) +
           chunk(b"IEND", b""))

    path = os.path.join(OUTPUT_DIR, f"icon-{size}.png")
    with open(path, "wb") as file:
        file.write(png)
    return path


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    (venues, opponents) = read_game_history()
    # Icons first: they are hashed into the build id, so they have to exist and
    # be current before the id is computed.
    written = [write_icon(192), write_icon(512)]
    seed_path = write_seed(venues, opponents)
    with open(seed_path, encoding="utf-8") as file:
        build = json.loads(file.read().split("= ", 1)[1].rstrip(";\n"))["build"]
    written += [seed_path,
                stamp("index.html", build),
                stamp("sw.js", build, cache_name=True)]
    for path in written:
        print(f"Wrote {path}")
    print(f"Build {build}")


if __name__ == "__main__":
    main()
